import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import "./globals.css";

const alice = Roboto({ 
  weight: '400', 
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={alice.className}>{children}</body>
      </AuthContextProvider>
      
    </html>
  );
}
